#!/bin/bash
# Version 1.61

# Load configuration file
probe="`cut -d "." -f 2 <<< $(hostname)`"
chprobe_configfile="/var/chprobe/chprobe.cfg"
source $chprobe_configfile

# basic
iptables -P INPUT ACCEPT
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT
iptables -A INPUT -i lo -m comment --comment loopback -j ACCEPT
iptables -A INPUT -m state --state INVALID -j DROP
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 68 -m comment --comment Allow-DHCP-Renew -j ACCEPT
iptables -I INPUT 1 -s 192.168.0.1/16 -p udp --dport 5353 -j ACCEPT

# comhem speedtest 
iptables -A INPUT -s 83.255.251.77 -j ACCEPT

# mgmt
iptables -A INPUT -s 83.255.225.1/24 -p icmp -j ACCEPT
iptables -A INPUT -s 83.248.145.173/32 -p icmp -j ACCEPT
iptables -A INPUT -s 192.168.0.1/32 -p tcp --dport 34521 -j ACCEPT
iptables -A INPUT -s 83.255.225.1/24 -p tcp --dport 34521 -j ACCEPT
iptables -A INPUT -s 83.248.145.173/32 -p tcp --dport 34521 -j ACCEPT
iptables -A INPUT -s 83.255.229.1/24 -j ACCEPT
iptables -A INPUT -s 94.137.97.98/32 -p tcp --dport 34521 -j ACCEPT
iptables -A INPUT -s $(cat /var/chprobe/ip-udp.txt) -p tcp --dport 34521 -j ACCEPT
iptables -A INPUT -s 213.89.17.164/32 -j ACCEPT

# Allow SSH from local subnets
iptables -A INPUT -s 192.168.0.1/24 -p tcp --dport 34521 -j ACCEPT
iptables -A INPUT -s 192.168.1.1/24 -p tcp --dport 34521 -j ACCEPT

# uPnP
iptables -A INPUT -s $(/sbin/ip route | awk '/default/ { print $3 }') -j ACCEPT

# Iperf3 server
if [ $chprobe_iperf3_localserver = "enable" ];then
iptables -A INPUT $chprobe_iperf3_firewall -j ACCEPT
fi

# Custom rules
if [ $chprobe_customrule = "enable" ]; then
OLDIFS=$IFS
IFS=$'\n'
for rules in ${chprobe_customfwrule[*]};do eval "iptables -A INPUT $rules -j ACCEPT"
done
IFS=$OLDIFS
fi

# drop rest
iptables -A INPUT -j DROP
