#!/bin/bash
# Version 0.5 (IPv6 support)
count=$(( ( RANDOM % 9999 )  + 100 ))

# Make sure we're not overloaded with scripts
while [ `pgrep -f 'chprobe_icmp|chprobe_multi|multi_chprobe|icmp_chprobe' | wc -l` -ge 80 ];do echo "[chprobe_error] We've got many scripts running. Some other script is hanging us or the host(s) is not very responsive. Sending SIGTERM to all scripts and trying to SIGINT daemons" | logger -p local5.err && kill $(pgrep -f "chprobe_icmp|chprobe_multi|multi_chprobe|icmp_chprobe" | awk '{print $1}') && kill -2 $(pgrep -f "ping" | awk '{print $1}'); done

# Wait until other daemons are done so we don't collide
while [ `pgrep -f 'bbk_cli|iperf3|wrk' | wc -w` -ge 20 ];do kill $(pgrep -f "iperf3|bbk_cli|wrk" | awk '{print $1}') && echo "[chprobe_error] We're overloaded with daemons, killing everything" | logger -p local5.err ; done
while [ `pgrep -f 'bbk_cli|tcp_iperf3' | wc -w` -ge 1 ];do sleep 1; done

while true
do
        case "$1" in
                -w)
shift
duration=$3
http_target=$4
threads=$1
connections=$2
http_target2=$(echo $http_target | sed "s/http://g" | tr -d '/')
wrk -t $threads -c $connections -d $duration $http_target | sed 's/ms/ /g' | egrep -v 'Thread|threads|Running' | xargs | sed "s/2xx//g" | sed "s/3xx//g" | tr -d ':|Requests|sec|Transfer|Socket|errors|requests|connect|read|write|,|timeout|Latency|Avg|Stdev|Max|+|-|/|Stdev|%|B|p|K|M|Non|-' | tr -s ' ' | sed -e "s/^/$(date "+%b %d %H:%M:%S") $(hostname -d) chprobe_wrk[$(echo $count)]: $threads $connections $http_target2/" >>/var/log/chprobe_wrk.log
                           ;;
                -e)
shift
ip_version=$2
if [ $ip_version = "4" ]; then service=echoping;elif [ $ip_version = "6" ]; then service=echoping_v6;fi # For tagging the log
http_target=$1
http_target2=$(echo $http_target | sed "s/http://g" | tr -d '/')
/usr/bin/echoping -P 0xa0 -$ip_version -p 6 -t 20 -w 1 -C -h / -A -a -R -n 5 $http_target | egrep 'Average|Maximum|Minimum|Median|Standard' | awk '{print $3}' | xargs | sed -e "s/^/$(date "+%b %d %H:%M:%S") $(hostname -d) chprobe_$service[$(echo $count)]: $http_target2 /" >>/var/log/chprobe_https.log
                       ;;
		-d)
shift
ip_version=$3
if [ $ip_version = "4" ]; then dnstag=dns;elif [ $ip_version = "6" ]; then dnstag=dns_v6;fi # For tagging the log
dns=$1
domain=$2
for z in {1..10};do
 for x in {TXT,MX,A,CNAME,AAAA};do /usr/bin/dig -$ip_version @$dns $domain $x && sleep 1;done | grep time | xargs | tr -d 'Query|time|msec|;;|:' | tr -s ' ' | sed -e "s/^/$(date "+%b %d %H:%M:%S") $(hostname -d) chprobe_$dnstag[$(echo $count)]: $dns $domain/" >>/var/log/chprobe_dns.log
done
;;
                                -h)  cat <<USAGE
usage: $0 [-e] [-w] [-h] [-d] args

    -h) See help
    -w) Use wrk binary 
    -e) Use echoping binary
    -d) Use dig binary
USAGE
            exit 1
            ;;
        *)
#            echo Use -h for help!
            break;
            ;;
    esac

    shift
done
