#!/bin/bash
# Install or update probe scripts
# Version 0.47 (20170713)
probeurl=http://project-mayhem.se/files/chprobe_latest_$(hostname -d).tgz
probedefaults=http://project-mayhem.se/files/chprobe_latest_general.tgz
probedir=/home/chprobe
managerurl=http://project-mayhem.se/files/probemanager

case "$1" in
  installation)
  yum install -y  wget iperf iperf3 &&
  echo 'Updating Manager'
  pushd $probedir/
  rm -f $probedir/probemanager*;sleep 1 && wget --no-cache $managerurl -P $probedir/ &&
 chmod +x $probedir/probemanager
  echo 'Downloading & installing probe'
  wget --no-cache $probeurl -P $probedir/ &&
  tar xvfz $probedir/chprobe_latest_$(hostname -d).tgz -C $probedir/ &&
  chmod +x $probedir/probe_settings
  chmod +x $probedir/fw-rules
  chmod +x $probedir/probemanager
  chmod +x $probedir/installdb
  chmod +x $probedir/installdb_udp
  chmod +x $probedir/smoke-slave
  chmod +x $probedir/smoke-slave-debug
  chmod +x $probedir/callhome.sh
  chmod +x $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2*
  chmod +x $probedir/upnpc-probe.sh
  chmod +x $probedir/icmp_chprobe
  echo "Backing up rc.local"
  cp /etc/rc.d/rc.local /etc/rc.d/rc.local.bak
  sleep 1
  echo "Done"
  sleep 1 &&
  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings
  /bin/bash $probedir/./installdb
  /bin/bash $probedir/./installdb_udp
  mv $probedir/fw-rules /root/fw-rules
  echo 'Updating Manager'
  rm -f $probedir/probemanager*; sleep 1 && wget --no-cache $managerurl -P $probedir/ &&
 chmod +x $probedir/probemanager
  echo '
# CHPROBE SSH
Port 34521' >> /etc/ssh/sshd_config
echo "We're done" && exit 0
    ;;
  update)
#  echo 'Updating Manager'
#  pushd $probedir/
#  rm -f $probedir/probemanager*; sleep 1; wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
#  echo 'Backing up probe'	# Don't do backups every update
#  tar cvfz chprobe_backup-$(date +"%d%m%y"-"%H%M" | tr -d '-').tgz $probedir/	# Don't do backups every update
  echo 'Downloading & updating probe'
  rm -f $probedir/chprobe_latest_$(hostname -d).tgz*; sleep 1 && wget --no-cache $probeurl -P $probedir/
  rm -f $probedir/version-* &&
  tar xvfz $probedir/chprobe_latest_$(hostname -d).tgz -C $probedir/ &&
  chmod +x $probedir/probe_settings
  chmod +x $probedir/fw-rules
  chmod +x $probedir/probemanager
  chmod +x $probedir/installdb
  chmod +x $probedir/installdb_udp
  chmod +x $probedir/smoke-slave
  chmod +x $probedir/smoke-slave-debug
  chmod +x $probedir/callhome.sh
  chmod +x $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2*
  chmod +x $probedir/upnpc-probe.sh
  chmod +x $probedir/icmp_chprobe  
  sleep 1 &&
#  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings
  mv $probedir/fw-rules /root/fw-rules
  iptables -F;/bin/bash /root/fw-rules
  curl -s $managerurl -O $probedir/;sleep 1 && 
chmod +x $probedir/probemanager
### Temporary space ###

# Set some global vars
export iperf3tcp_log="/var/log/iperf3tcp.log"
export iperf3udp_log="/var/log/iperf3udp.log"
# Enable strict mode permanently
# echo "export strict_mode=true" >> /etc/profile.d/chprobe_settings.sh

## Remove probemanager from git repo
  rm $probedir/probemanager_unofficial > /dev/null
#  rm $probedir/chprobe_latest_*.tgz
## Install motd and fix permissions for it
  chown -R chprobe:chprobe /var/log/chprobe*
  chown -R chprobe:chprobe /var/log/iperf*
  curl http://project-mayhem.se/probes/chprobe_motd.sh -o /etc/profile.d/chprobe.sh
  head -n 1 /home/chprobe/version-* | grep -oP '"\K[^"\047]+(?=["\047])' > /etc/chprobe_version

## Alias for debugging collisions
echo "clear && echo '### START ###' && { journalctl -n 50000 | egrep 'iperf3|bbk' | egrep 'Finished|Starting'; tail -n 200 /var/log/chprobe_bbk.log; tail -n 200 /var/log/iperf3tcp.log; } | sort && echo '### END ###'" > /usr/local/sbin/chprobe_collisiondebug && chmod +x /usr/local/sbin/chprobe_collisiondebug

##  Create backupdir
#  mkdir /root/backups

## Install new filebeat config
#  mv $probedir/filebeat.yml /etc/filebeat/filebeat.yml
#  systemctl restart filebeat

##  Install wrk binary (chprobe version)
#  wget --no-cache http://project-mayhem.se/files/wrk_binary-x86.tgz -P /root/ &&
#  tar xvfz /root/wrk_binary-x86.tgz -C /usr/bin/
#  rm -Rf /root/wrk_binary-x86.tgz*

### Temporary space ###
  echo "We're done" && exit 0
    ;;
  restoredefault)
  echo 'Updating Manager'
  pushd $probedir/
  rm -f $probedir/probemanager*;sleep 1 && wget --no-cache $managerurl -P $probedir/ && sleep 5 &&
chmod +x $probedir/probemanager
  echo 'Cleaning up'
  rm -Rf $probedir/* /etc/rc.d/rc.local
  echo 'Downloading & installing probe with default settings'
  sleep 1 &&
  wget --no-cache $probedefaults -P $probedir/ &&
  tar xvfz $probedir/chprobe_latest_general.tgz -C $probedir/ &&
  chmod +x $probedir/probe_settings
  chmod +x $probedir/fw-rules
  chmod +x $probedir/probemanager
  chmod +x $probedir/installdb
  chmod +x $probedir/installdb_udp
  chmod +x $probedir/smoke-slave
  chmod +x $probedir/smoke-slave-debug
  chmod +x $probedir/callhome.sh
  chmod +x $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2*
  chmod +x $probedir/upnpc-probe.sh
  chmod +x $probedir/icmp_chprobe
  echo "Backing up rc.local"
  cp /etc/rc.d/rc.local /etc/rc.d/rc.local.bak
  sleep 1
  echo "Done"
  sleep 1 &&
  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings
  mv $probedir/fw-rules /root/fw-rules
#  /bin/bash $probedir/./installdb # Uncomment if you want to reset the db
#  /bin/bash $probedir/./installdb_udp # Uncomment if you want to reset the db
  echo 'Updating Manager'
  rm -f $probedir/probemanager; sleep 1 && wget --no-cache $managerurl -P $probedir/ && sleep 1 &&
 chmod +x $probedir/probemanager
  echo "We're done" && exit 0
    ;;
  managerupdate)
  echo 'Updating Manager'
  pushd $probedir/
  curl -s $managerurl -O $probedir/;sleep 1 &&
 chmod +x $probedir/probemanager && exit 0
    ;;
  *)
    echo "Usage: $0 {installation|update|restoredefault|managerupdate}" >&2
    exit 1
    ;;
esac
