#!/bin/bash
# crontab
echo "SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed" > /etc/crontab
# echo "*/6  *  *  *  * root /home/chprobe/./udp_iperf3_client.sh > /dev/null"  >> /etc/crontab
# echo "*/5  *  *  *  * root /home/chprobe/./udp_iperf3_client_reversed.sh > /dev/null"  >> /etc/crontab
echo "*/16 *  *  *  * root /home/chprobe/./tcp_iperf3_client.sh > /dev/null" >> /etc/crontab
echo "*/15 *  *  *  * root /home/chprobe/./tcp_iperf3_client_reversed.sh > /dev/null" >> /etc/crontab
echo "*/30 *  *  *  * root /home/chprobe/./upnpc-probe.sh > /dev/null" >> /etc/crontab
echo "5  7   *  *  6  root /home/chprobe/./probemanager update > /dev/null" >> /etc/crontab
echo "5  8   *  1  *  root rm /home/chprobe/chprobe_backup* > /dev/null" >> /etc/crontab

# rc.local
echo "Backing up rc.local"
cp /etc/rc.d/rc.local /etc/rc.d/rc.local.bak
sleep 1
echo "Done"
echo "Installing probe rc.local"
echo "/root/./fw-rules"                         >> /etc/rc.local
echo "/home/chprobe/./smoke-slave"              >> /etc/rc.local
echo "/home/chprobe/./probemanager"             >> /etc/rc.local
# echo "# darkstat -i enp0s25 -p 35631 --syslog"    >> /etc/rc.local
chmod +x /etc/rc.d/rc.local
systemctl restart crond
echo "Mission complete."
