#!/bin/bash
# Install or update probe scripts
# Version 0.37
probeurl=http://project-mayhem.se/files/chprobe_latest_$(hostname -d).tgz
probedefaults=http://project-mayhem.se/files/chprobe_latest_general.tgz
probedir=/home/chprobe
managerurl=http://project-mayhem.se/files/probemanager

case "$1" in
  installation)
  echo 'Updating Manager'
  pushd $probedir/
  rm -f $probedir/probemanager*;sleep 1; wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
  echo 'Downloading & installing probe'
  wget --no-cache $probeurl -P $probedir/
  sleep 10
  tar xvfz $probedir/chprobe_latest_$(hostname -d).tgz -C $probedir/
  sleep 5
  chmod +x $probedir/probe_settings
  chmod +x $probedir/fw-rules
  chmod +x $probedir/probemanager
  chmod +x $probedir/installdb
  chmod +x $probedir/installdb_udp
  chmod +x $probedir/smoke-slave
  chmod +x $probedir/smoke-slave-debug
  chmod +x $probedir/smokeslave_fakepost
  chmod +x $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2*
  chmod +x $probedir/upnpc-probe.sh
  echo "Backing up rc.local"
  cp /etc/rc.d/rc.local /etc/rc.d/rc.local.bak
  sleep 1
  echo "Done"
  sleep 1
  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings
  /bin/bash $probedir/./installdb
  /bin/bash $probedir/./installdb_udp
  mv $probedir/fw-rules /root/fw-rules
  echo 'Updating Manager'
  rm -f $probedir/probemanager*; sleep 1;wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
  echo '
# CHPROBE SSH
Port 34521' >> /etc/ssh/sshd_config
echo "We're done"
    ;;
  update)
  echo 'Updating Manager'
  pushd $probedir/
  rm -f $probedir/probemanager*; sleep 1; wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
  echo 'Backing up probe'
  tar cvfz chprobe_backup-$(date +"%d%m%y"-"%H%M" | tr -d '-').tgz $probedir/
  echo 'Downloading & updating probe'
  rm -f $probedir/chprobe_latest_$(hostname -d).tgz*; sleep 1; wget --no-cache $probeurl -P $probedir/
  sleep 10
  tar xvfz $probedir/chprobe_latest_$(hostname -d).tgz -C $probedir/
  sleep 5
  chmod +x $probedir/probe_settings
  chmod +x $probedir/fw-rules
  chmod +x $probedir/probemanager
  chmod +x $probedir/installdb
  chmod +x $probedir/installdb_udp
  chmod +x $probedir/smoke-slave
  chmod +x $probedir/smoke-slave-debug
  chmod +x $probedir/smokeslave_fakepost
  chmod +x $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2*
  chmod +x $probedir/upnpc-probe.sh
  sleep 1
#  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings
  mv $probedir/fw-rules /root/fw-rules
  rm -f $probedir/probemanager*; sleep 1; wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
  echo "We're done"
    ;;
  restoredefault)
  echo 'Updating Manager'
  pushd $probedir/
  rm -f $probedir/probemanager*;sleep 1;wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
  echo 'Cleaning up'
  rm -Rf $probedir/* /etc/rc.d/rc.local
  echo 'Downloading & installing probe with default settings'
  sleep 1
  wget --no-cache $probedefaults -P $probedir/
  sleep 10
  tar xvfz $probedir/chprobe_latest_general.tgz -C $probedir/
  sleep 5
  chmod +x $probedir/probe_settings
  chmod +x $probedir/fw-rules
  chmod +x $probedir/probemanager
  chmod +x $probedir/installdb
  chmod +x $probedir/installdb_udp
  chmod +x $probedir/smoke-slave
  chmod +x $probedir/smoke-slave-debug
  chmod +x $probedir/smokeslave_fakepost
  chmod +x $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2*
  chmod +x $probedir/upnpc-probe.sh
  echo "Backing up rc.local"
  cp /etc/rc.d/rc.local /etc/rc.d/rc.local.bak
  sleep 1
  echo "Done"
  sleep 1
  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings
  mv $probedir/fw-rules /root/fw-rules
#  /bin/bash $probedir/./installdb # Uncomment if you want to reset the db
#  /bin/bash $probedir/./installdb_udp # Uncomment if you want to reset the db
  echo 'Updating Manager'
  rm -f $probedir/probemanager; sleep 1;wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
  echo "We're done"
    ;;
  *)
    echo "Usage: $0 {installation|update|restoredefault}" >&2
    exit 1
    ;;
esac
