#!/bin/bash
# Install or update probe scripts
# Version 0.53 (20180915)
probename="`cut -d "." -f 2 <<< $(hostname)`"
probeurl=http://project-mayhem.se/files/chprobe_latest_${probename}.tgz
probedefaults=http://project-mayhem.se/files/chprobe_latest_general.tgz
source /var/chprobe/chprobe.cfg || probedir="/home/chprobe"
managerurl=http://project-mayhem.se/files/probemanager
# configurl=http://project-mayhem.se/probes/chprobe_cfg/${probename}.cfg # Disabled
global_configurl=http://project-mayhem.se/probes/chprobe_cfg/global.cfg

case "$1" in
  installation)
  echo 'Updating Manager'
  pushd $probedir/
  rm -f $probedir/probemanager*;sleep 1 && wget --no-cache $managerurl -P $probedir/ &&
  chmod +x $probedir/probemanager
  echo 'Downloading & installing probe'
  wget --no-cache $probeurl -P $probedir/ &&
  tar xvfz $probedir/chprobe_latest_${probename}.tgz -C $probedir/ &&
  chmod +x $probedir/probe_settings $probedir/fw-rules $probedir/probemanager $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2* $probedir/upnpc-probe.sh $probedir/icmp_chprobe $probedir/bbk_chprobe
  echo "Backing up rc.local"
  cp /etc/rc.d/rc.local /etc/rc.d/rc.local.bak
  mkdir /root/backups
  sleep 1
  echo "Done"
  sleep 1 &&
  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings -s
  mv $probedir/fw-rules /root/fw-rules
  echo 'Updating Manager'
  rm -f $probedir/probemanager*; sleep 1 && wget --no-cache $managerurl -P $probedir/ &&
 chmod +x $probedir/probemanager
  echo '
# CHPROBE SSH
Port 34521' >> /etc/ssh/sshd_config
echo "We're done" && exit 0
    ;;
  update)
# Install config files and motd
curl -m 3 --retry 2 -s $global_configurl -o /var/chprobe/global.cfg && chmod +x /var/chprobe/global.cfg
chown -R chprobe:chprobe /var/chprobe
curl http://project-mayhem.se/probes/chprobe_motd.sh -o /var/chprobe/chprobe.sh
#  echo 'Updating Manager'
#  pushd $probedir/
#  rm -f $probedir/probemanager*; sleep 1; wget --no-cache $managerurl -P $probedir/;sleep 5;chmod +x $probedir/probemanager
#  echo 'Backing up probe'	# Don't do backups every update
#  tar cvfz chprobe_backup-$(date +"%d%m%y"-"%H%M" | tr -d '-').tgz $probedir/	# Don't do backups every update
  echo 'Downloading & updating probe'
  rm -f $probedir/chprobe_latest_${probename}.tgz*; sleep 1 && wget --no-cache $probeurl -P $probedir/
  rm -f $probedir/version-* &&
  tar xvfz $probedir/chprobe_latest_${probename}.tgz -C $probedir/ &&
  sleep 1 &&
  mv $probedir/fw-rules /root/fw-rules
  iptables -F;/bin/bash /root/fw-rules
  curl -s $managerurl -O $probedir/;sleep 1 && 
  chmod +x $probedir/probemanager
  bash /var/chprobe/global.cfg
  bash $probedir/./probe_settings -s
### Temporary space ###

## Install motd and fix permissions for it
  chown -R chprobe:chprobe /var/log/chprobe*
  chown -R chprobe:chprobe /var/log/iperf*
  head -n 1 $probedir/version-* | grep -oP '"\K[^"\047]+(?=["\047])' > /etc/chprobe_version

##  Install wrk binary (chprobe version)
#  wget --no-cache http://project-mayhem.se/files/wrk_binary-x86.tgz -P /root/ &&
#  tar xvfz /root/wrk_binary-x86.tgz -C /usr/bin/
#  rm -Rf /root/wrk_binary-x86.tgz*

# Copy chprobe cfg file to change filename (v23+)
if [ `grep -c 0.96.24 /etc/chprobe_version 2> /dev/null` 2> /dev/null -eq 1 ]; then
#/bin/cp -f /var/chprobe/${probename}.cfg /var/chprobe/chprobe.cfg && /bin/rm -f /var/chprobe/${probename}.cfg
/bin/rm -f /var/chprobe/${probename}.cfg &> /dev/null
$probedir/./probe_settings -s
fi

### Temporary space ###
  echo "We're done" && exit 0
    ;;
  restoredefault)
  echo 'Updating Manager'
  pushd $probedir/
  rm -f $probedir/probemanager*;sleep 1 && wget --no-cache $managerurl -P $probedir/ && sleep 5 &&
chmod +x $probedir/probemanager
  echo 'Cleaning up'
  rm -Rf $probedir/* /etc/rc.d/rc.local
  echo 'Downloading & installing probe with default settings'
  sleep 1 &&
  wget --no-cache $probedefaults -P $probedir/ &&
  tar xvfz $probedir/chprobe_latest_general.tgz -C $probedir/ &&
  chmod +x $probedir/probe_settings $probedir/fw-rules $probedir/probemanager $probedir/udp_iperf3* $probedir/udp_iperf2* $probedir/tcp_iperf3* $probedir/tcp_iperf2* $probedir/upnpc-probe.sh $probedir/icmp_chprobe $probedir/bbk_chprobe
  echo "Backing up rc.local"
  cp /etc/rc.d/rc.local /etc/rc.d/rc.local.bak
  sleep 1
  echo "Done"
  sleep 1 &&
  /bin/bash $probedir/./upnpc-probe.sh
  /bin/bash $probedir/./probe_settings -s
  mv $probedir/fw-rules /root/fw-rules
  echo 'Updating Manager'
  rm -f $probedir/probemanager; sleep 1 && wget --no-cache $managerurl -P $probedir/ && sleep 1 &&
 chmod +x $probedir/probemanager
  echo "We're done" && exit 0
    ;;
  managerupdate)
  echo 'Updating Manager'
  pushd $probedir/
  curl -s $managerurl -O $probedir/;sleep 1 &&
 chmod +x $probedir/probemanager && exit 0
    ;;
  backup)
  tar cvfz /root/backups/chprobe_backup-$(date +"%d%m%y"-"%H%M" | tr -d '-').tgz $probedir &> /dev/null
  echo 'Done with backup'
  exit 0
   ;;
  *)
    echo "Usage: $0 {installation|update|restoredefault|managerupdate|backup}" >&2
    exit 1
    ;;
esac
